### ISSUE TITLE
clientHold / serverHold

### ISSUE THREAD

**Issue by dnsguru** [groundcat/PSL-private-domains-checker#1]
This checker is fire.  Thank you.

Domains in clientHold or serverHold are typically ones that earned it in a bad way, which should be considered for removal from PSL.

Is it possible to also make a csv that outputs the domains where you can find Hold in the whois response?

It can be done with the current data set.

**Comment by groundcat** [comment]
Thank you for the feedback! I will implement a `hold` filter soon, which will dump `data/hold.csv` with domains that are possibly put on clientHold/serverHold.

**Comment by groundcat** [comment]
Added filter to find domains with any type of hold status and exported the results to hold.csv
- [Updated dataset](https://github.com/groundcat/PSL-private-domains-checker/tree/main/data)
